# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{refinerycms-translations}
  s.version = "0.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Charles Barbier", "season", "Victor Castell"]
  s.date = %q{2011-05-26}
  s.description = %q{Simple approach to content translation for RefineryCMS}
  s.email = %q{unixcharles@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    "app/controllers/admin/translations_controller.rb",
    "app/controllers/translations_controller.rb.txt",
    "app/models/translation.rb",
    "app/views/admin/translations/_form.html.erb",
    "app/views/admin/translations/_sortable_list.html.erb",
    "app/views/admin/translations/_translation.html.erb",
    "app/views/admin/translations/edit.html.erb",
    "app/views/admin/translations/index.html.erb",
    "app/views/admin/translations/new.html.erb",
    "app/views/translations/index.html.erb",
    "app/views/translations/show.html.erb",
    "config/locales/en.yml",
    "config/routes.rb",
    "lib/generators/refinerycms_translations_generator.rb",
    "lib/refinerycms-translations.rb"
  ]
  s.homepage = %q{http://github.com/unixcharles/refinerycms-translations}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{RefineryCMS Translations engine}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
  end
end

